### PR TITLE
Merge recently-synced upstream main into our release

### PR DESCRIPTION
**Pull request by chris-bridgett-nandos**

### CODE REVIEW

**Comment by chris-bridgett-nandos** [comment]
_Confusion intensifies_

I cannot get tests to pass on _any_ branch, in _any_ environment. Google's last successful test run was 2 months ago. Before I reach out to them, does anyone have a moment to humour me and try running tests?

@nav-nandos @matthew-green-nandos 

AFAIK this PR will work (and bring us up to date), albeit with failing tests.

It will also provision a grafana dashboard, since that's now part of the upstream `main`... whilst we won't use that internally, wouldn't hurt to have that, in terms of making contributions back that will also need to factor in said dashboard?

**Comment by nav-nandos** [comment]
> 

@chris-bridgett-nandos  We can look together those failures.

**Comment by matthew-green-nandos** [comment]
> _Confusion intensifies_
> 
> I cannot get tests to pass on _any_ branch, in _any_ environment. Google's last successful test run was 2 months ago. Before I reach out to them, does anyone have a moment to humour me and try running tests?
> 
> @nav-nandos @matthew-green-nandos
> 
> AFAIK this PR will work (and bring us up to date), albeit with failing tests.

It seem to have changed from `warning` to `error` and this is due to us using `ItsDangerous >= 2.1`. Therefore we will need to fix the version as @nav-nandos has suggested (do you have the reference that suggested the fix?). I think it is okay to fix our branch but will be confusing when we push back.


> It will also provision a grafana dashboard, since that's now part of the upstream `main`... whilst we won't use that internally, wouldn't hurt to have that, in terms of making contributions back that will also need to factor in said dashboard?

IMHO, I would make it optional and not deploy it to stop people thinking we are heading in that direction.

**Comment by nav-nandos** [comment]
> > _Confusion intensifies_
> > I cannot get tests to pass on _any_ branch, in _any_ environment. Google's last successful test run was 2 months ago. Before I reach out to them, does anyone have a moment to humour me and try running tests?
> > @nav-nandos @matthew-green-nandos
> > AFAIK this PR will work (and bring us up to date), albeit with failing tests.
> 
> It seem to have changed from `warning` to `error` and this is due to us using `ItsDangerous >= 2.1`. Therefore we will need to fix the version as @nav-nandos has suggested (do you have the reference that suggested the fix?). I think it is okay to fix our branch but will be confusing when we push back.
> 
> > It will also provision a grafana dashboard, since that's now part of the upstream `main`... whilst we won't use that internally, wouldn't hurt to have that, in terms of making contributions back that will also need to factor in said dashboard?
> 
> IMHO, I would make it optional and not deploy it to stop people thinking we are heading in that direction.

@matthew-green-nandos  i can check on local for removal of itsdangerous package by upgrading flask in my local env.

**Comment by matthew-green-nandos** [comment]
> @matthew-green-nandos i can check on local for removal of itsdangerous package by upgrading flask in my local env.

@nav-nandos , I don't think we should upgrade flask but pin the version of `itsdangerous` that has the `json` module. This is what I would do normally when developing a Python web app.

**Pull request closed without merging**
